TTK4235 Elevator Project: project/src/fsm.c File Reference
fsm.c File Reference
#include "fsm.h"
#include <string.h>
#include "driver/elevio.h"
#include "lib/log.h"
#include "elevatorState.h"
#include "movement.h"
#include "hmi.h"
#include "timer.h"
#include "utils.h"
Functions
static void fsm_onInit (void)
static void fsm_onIdle (void)
static void fsm_onMoving (void)
static void fsm_onDoorOpen (void)
static void fsm_onStop (void)
void fsm_spin (void)
Executes one single tick of the elevator's state machine.
Variables
static ElevatorState elevator
Function Documentation
fsm_onDoorOpen()
static void fsm_onDoorOpen (void) static
Definition at line 88 of file fsm.c.
References areAllElementsFalse(), ElevatorState::currentFloor, ElevatorState::currentState, ElevatorState::doorOpenTimer, elevator, ElevatorState::orderArr, ElevatorState::prevFloor, STATE_IDLE, STATE_MOVING, timer_isTimeout(), timer_start(), and timer_stop().
Referenced by fsm_spin().
fsm_onIdle()
static void fsm_onIdle (void) static
Definition at line 49 of file fsm.c.
References areAllElementsFalse(), ElevatorState::currentDir, ElevatorState::currentState, elevator, ElevatorState::orderArr, and STATE_MOVING.
Referenced by fsm_spin().
fsm_onInit()
static void fsm_onInit (void) static
Definition at line 19 of file fsm.c.
References ElevatorState::currentFloor, ElevatorState::currentState, elevator, elevatorState_init(), ElevatorState::prevFloor, STATE_IDLE, and timer_msSleep().
Referenced by fsm_spin().
fsm_onMoving()
static void fsm_onMoving (void) static
Definition at line 64 of file fsm.c.
References ElevatorState::currentFloor, ElevatorState::currentState, elevator, movement_directionHandler(), movement_recoveryHandler(), movement_stopHandler(), and STATE_DOOR_OPEN.
Referenced by fsm_spin().
fsm_onStop()
static void fsm_onStop (void) static
Definition at line 128 of file fsm.c.
References ElevatorState::currentDir, ElevatorState::currentFloor, ElevatorState::currentState, elevator, ElevatorState::isStopped, ElevatorState::orderArr, ElevatorState::prevBtnStates, STATE_DOOR_OPEN, and STATE_IDLE.
Referenced by fsm_spin().
fsm_spin()
void fsm_spin (void)
Executes one single tick of the elevator's state machine.
This function should be called continuously in the main program loop (e.g., inside main.c's while(1)). During each spin, it polls the hardware for floor updates and stop button presses, conditionally queries for new orders, and then triggers the appropriate internal state handler based on elevator.currentState. Finally, it updates the previous floor tracking before yielding.
Definition at line 157 of file fsm.c.
References ElevatorState::btnQueryTimer, ElevatorState::currentFloor, ElevatorState::currentState, elevator, fsm_onDoorOpen(), fsm_onIdle(), fsm_onInit(), fsm_onMoving(), fsm_onStop(), hmi_floorHandler(), hmi_orderHandler(), hmi_stopBtnHandler(), ElevatorState::prevFloor, STATE_DOOR_OPEN, STATE_IDLE, STATE_INIT, STATE_MOVING, STATE_STOP, timer_isTimeout(), timer_start(), and timer_stop().
Referenced by main().
Variable Documentation
elevator
ElevatorState elevator static
Definition at line 15 of file fsm.c.
Referenced by fsm_onDoorOpen(), fsm_onIdle(), fsm_onInit(), fsm_onMoving(), fsm_onStop(), and fsm_spin().