TTK4235 Elevator Project: project/src/fsm.h File Reference
fsm.h File Reference
Main finite state machine (FSM) loop for the elevator.
Functions
void fsm_spin (void)
Executes one single tick of the elevator's state machine.
Detailed Description
Main finite state machine (FSM) loop for the elevator.
This module orchestrates the elevator's behavior. It acts as the central nervous system, pulling in hardware readings from the HMI module, routing decisions through the movement module, and dispatching execution to internal state handlers (Init, Idle, Moving, Door Open, Stop).
Definition in file fsm.h.
Function Documentation
fsm_spin()
void fsm_spin (void)
Executes one single tick of the elevator's state machine.
This function should be called continuously in the main program loop (e.g., inside main.c's while(1)). During each spin, it polls the hardware for floor updates and stop button presses, conditionally queries for new orders, and then triggers the appropriate internal state handler based on elevator.currentState. Finally, it updates the previous floor tracking before yielding.
Definition at line 157 of file fsm.c.
References ElevatorState::btnQueryTimer, ElevatorState::currentFloor, ElevatorState::currentState, elevator, fsm_onDoorOpen(), fsm_onIdle(), fsm_onInit(), fsm_onMoving(), fsm_onStop(), hmi_floorHandler(), hmi_orderHandler(), hmi_stopBtnHandler(), ElevatorState::prevFloor, STATE_DOOR_OPEN, STATE_IDLE, STATE_INIT, STATE_MOVING, STATE_STOP, timer_isTimeout(), timer_start(), and timer_stop().
Referenced by main().