TTK4235 Elevator Project: project/src/hmi.c File Reference
hmi.c File Reference
Implementation of the Human-Machine Interface logic.
#include "hmi.h"
Functions
void hmi_stopBtnHandler (ElevatorState *elev)
Polls the emergency stop button and manages stop state transitions.
void hmi_floorHandler (ElevatorState *elev)
Reads the current floor sensor and updates the hardware indicator.
void hmi_orderHandler (ElevatorState *elev)
Polls all request buttons and registers new elevator orders.
Detailed Description
Implementation of the Human-Machine Interface logic.
Definition in file hmi.c.
Function Documentation
hmi_floorHandler()
void hmi_floorHandler (ElevatorState * elev)
Reads the current floor sensor and updates the hardware indicator.
Polls the hardware to see if the elevator is currently at a valid floor. If it is, it updates the central state and changes the physical floor indicator lamp on the elevator panel.
Parameters
[in,out] elev Pointer to the central elevator state structure.
Retrieves the sensor reading via elevio_floorSensor(). If the elevator is between floors, the sensor returns -1, and the floor indicator is left at its previous valid value. Updates to the indicator lamp are suppressed during STATE_INIT.
Definition at line 40 of file hmi.c.
References ElevatorState::currentFloor, ElevatorState::currentState, and STATE_INIT.
Referenced by fsm_spin().
hmi_orderHandler()
void hmi_orderHandler (ElevatorState * elev)
Polls all request buttons and registers new elevator orders.
Iterates through all possible floor and cabin buttons. If a valid new press is detected, it registers the order in the state matrix and illuminates the corresponding button lamp.
Parameters
[in,out] elev Pointer to the central elevator state structure.
Note
Orders are ignored if the elevator is currently stopped or debouncing from a stop command.
Iterates through the N_FLOORS x N_BUTTONS matrix. To prevent a single long button press from registering continuously, this function uses rising edge detection: an order is only registered if the button is currently pressed AND was not pressed in the previous polling cycle. Active inputs are strictly ignored if the stop button is active or still debouncing.
Definition at line 50 of file hmi.c.
References ElevatorState::isStopDebouncing, ElevatorState::isStopPressed, ElevatorState::orderArr, and ElevatorState::prevBtnStates.
Referenced by fsm_spin().
hmi_stopBtnHandler()
void hmi_stopBtnHandler (ElevatorState * elev)
Polls the emergency stop button and manages stop state transitions.
Checks the physical state of the stop button, handles the necessary debouncing, and transitions the elevator into the emergency stop state if activated. It also controls the stop button illumination.
Parameters
[in,out] elev Pointer to the central elevator state structure.
Precondition
The elevator state must be initialized.
If the elevator is in STATE_INIT, stop inputs are ignored to prevent startup anomalies. When the physical stop button is pressed, the stop lamp is activated, a debounce timer is started, and the system is immediately forced into STATE_STOP. The system remains in a debouncing state until the physical button is released and the timer expires, at which point the lamp clears and normal operation can resume.
Definition at line 9 of file hmi.c.
References ElevatorState::currentState, ElevatorState::isStopDebouncing, ElevatorState::isStopPressed, STATE_INIT, STATE_STOP, ElevatorState::stopDebouncerTimer, timer_isTimeout(), timer_start(), and timer_stop().
Referenced by fsm_spin().