TTK4235 Elevator Project: project/src/movement.h File Reference
movement.h File Reference
Handles elevator routing, stopping logic, and direction calculation.
#include "elevatorState.h"
Functions
bool movement_requestsAbove (ElevatorState *elev, int floor)
Checks if there are any active orders above a specific floor.
bool movement_requestsBelow (ElevatorState *elev, int floor)
Checks if there are any active orders below a specific floor.
bool movement_recoveryHandler (ElevatorState *elev)
Determines the initial direction if the elevator is halted between floors.
bool movement_stopHandler (ElevatorState *elev)
Evaluates whether the elevator should halt at the current floor.
void movement_directionHandler (ElevatorState *elev)
Calculates and applies the next motor direction based on active orders.
Detailed Description
Handles elevator routing, stopping logic, and direction calculation.
This module implements the core elevator algorithm (the LOOK algorithm). It determines when the elevator should stop, which direction it should travel next based on active orders, and how to recover if halted between floors.
Definition in file movement.h.
Function Documentation
movement_directionHandler()
void movement_directionHandler (ElevatorState * elev)
Calculates and applies the next motor direction based on active orders.
Parameters
[in,out] elev Pointer to the central elevator state structure.
Checks for remaining requests in the current direction of travel. If orders remain, it continues in that direction. If the path is clear, it reverses direction to serve orders behind it. If the entire queue is empty, it stops the motor and transitions the system into STATE_IDLE.
Definition at line 86 of file movement.c.
References ElevatorState::currentDir, ElevatorState::currentFloor, ElevatorState::currentState, movement_requestsAbove(), movement_requestsBelow(), ElevatorState::prevDir, and STATE_IDLE.
Referenced by fsm_onMoving().
movement_recoveryHandler()
bool movement_recoveryHandler (ElevatorState * elev)
Determines the initial direction if the elevator is halted between floors.
Parameters
[in,out] elev Pointer to the central elevator state structure.
Returns
true if a recovery was necessary and handled.
false if the elevator is not in a recovery state.
If the elevator is stopped between floors (sensor reads -1) and a new order is placed, this function uses the previous direction and previous floor to calculate whether it is "hovering" above or below a floor. It then routes the elevator safely to the nearest requested floor without skipping orders.
Definition at line 25 of file movement.c.
References ElevatorState::currentDir, ElevatorState::currentFloor, ElevatorState::isStopped, movement_requestsAbove(), movement_requestsBelow(), ElevatorState::orderArr, ElevatorState::prevDir, and ElevatorState::prevFloor.
Referenced by fsm_onMoving().
movement_requestsAbove()
bool movement_requestsAbove (ElevatorState * elev, int floor)
Checks if there are any active orders above a specific floor.
Parameters
[in] elev Pointer to the central elevator state structure.
[in] floor The reference floor to check above.
Returns
true if there is at least one active order on a higher floor.
false if the order array is clear for all floors above.
Iterates through the order matrix from floor + 1 up to the highest possible floor, checking cabin, hall up, and hall down buttons.
Definition at line 8 of file movement.c.
References ElevatorState::orderArr.
Referenced by movement_directionHandler(), movement_recoveryHandler(), and movement_stopHandler().
movement_requestsBelow()
bool movement_requestsBelow (ElevatorState * elev, int floor)
Checks if there are any active orders below a specific floor.
Parameters
[in] elev Pointer to the central elevator state structure.
[in] floor The reference floor to check below.
Returns
true if there is at least one active order on a lower floor.
false if the order array is clear for all floors below.
Iterates through the order matrix from floor 0 up to floor - 1, checking cabin, hall up, and hall down buttons.
Definition at line 16 of file movement.c.
References ElevatorState::orderArr.
Referenced by movement_directionHandler(), movement_recoveryHandler(), and movement_stopHandler().
movement_stopHandler()
bool movement_stopHandler (ElevatorState * elev)
Evaluates whether the elevator should halt at the current floor.
Parameters
[in] elev Pointer to the central elevator state structure.
Returns
true if the elevator should stop at this floor.
false if the elevator should bypass this floor.
Implements the core stopping logic: Always stops for cabin calls. If moving UP, it stops for UP hall calls, or DOWN hall calls if it is the highest active request. If moving DOWN, it stops for DOWN hall calls, or UP hall calls if it is the lowest active request.
Definition at line 65 of file movement.c.
References ElevatorState::currentDir, ElevatorState::currentFloor, movement_requestsAbove(), movement_requestsBelow(), and ElevatorState::orderArr.
Referenced by fsm_onMoving().