TTK4235 Elevator Project: project/src/timer.h File Reference
timer.h File Reference
Provides non-blocking timers and blocking sleep functions.
#include <stdbool.h>
#include <sys/time.h>
#include <stddef.h>
#include <time.h>
Data Structures
struct timerAlarm
Represents a non-blocking timer instance.
Functions
double timer_getWallTime (void)
Retrieves the current system wall time in seconds.
void timer_init (timerAlarm *timerAlarmInstance)
Initializes a timer instance to a safe default state.
void timer_start (timerAlarm *timerAlarmInstance, double duration)
Starts a timer for a specified duration.
void timer_stop (timerAlarm *timerAlarmInstance)
Forcibly stops a running timer.
bool timer_isTimeout (timerAlarm *timerAlarmInstance)
Checks if an active timer has expired.
void timer_msSleep (long ms)
Blocks program execution for a specified duration.
Detailed Description
Provides non-blocking timers and blocking sleep functions.
Definition in file timer.h.
Function Documentation
timer_getWallTime()
double timer_getWallTime (void)
Retrieves the current system wall time in seconds.
Returns
The current time in seconds as a double-precision float.
Fetches the time using gettimeofday. The seconds and microseconds are combined into a single value. The mathematical conversion used is $t_{sec} = s + \mu s \times 10^{-6}$ .
Definition at line 7 of file timer.c.
Referenced by timer_isTimeout(), timer_start(), and timer_stop().
timer_init()
void timer_init (timerAlarm * timerAlarmInstance)
Initializes a timer instance to a safe default state.
Parameters
[out] timerAlarmInstance Pointer to the timer instance to initialize.
Forces the timer to an inactive state and clears the end time. This should be called once before attempting to start or check the timer.
Definition at line 15 of file timer.c.
References timerAlarm::timerActive, and timerAlarm::timerEndTime.
Referenced by elevatorState_init().
timer_isTimeout()
bool timer_isTimeout (timerAlarm * timerAlarmInstance)
Checks if an active timer has expired.
Parameters
[in] timerAlarmInstance Pointer to the timer instance to check.
Returns
true if the timer is active AND the current wall time has passed the end time.
false if the timer is inactive or the time has not yet expired.
This is a non-blocking check. It relies on polling the current wall time against the stored expiration time.
Definition at line 33 of file timer.c.
References timer_getWallTime(), timerAlarm::timerActive, and timerAlarm::timerEndTime.
Referenced by fsm_onDoorOpen(), fsm_spin(), and hmi_stopBtnHandler().
timer_msSleep()
void timer_msSleep (long ms)
Blocks program execution for a specified duration.
Parameters
[in] ms The number of milliseconds to sleep.
Uses nanosleep to suspend the thread. This is a blocking delay and will halt the main execution loop, unlike the non-blocking timerAlarm functions.
Definition at line 37 of file timer.c.
Referenced by fsm_onInit().
timer_start()
void timer_start (timerAlarm * timerAlarmInstance, double duration)
Starts a timer for a specified duration.
Parameters
[in,out] timerAlarmInstance Pointer to the timer instance.
[in] duration The amount of time to run the timer for, in seconds.
Calculates the absolute end time based on the current wall time plus the requested duration. If the timer is already active, this function returns immediately without overwriting the running timer.
Definition at line 20 of file timer.c.
References timer_getWallTime(), timerAlarm::timerActive, and timerAlarm::timerEndTime.
Referenced by fsm_onDoorOpen(), fsm_spin(), and hmi_stopBtnHandler().
timer_stop()
void timer_stop (timerAlarm * timerAlarmInstance)
Forcibly stops a running timer.
Parameters
[in,out] timerAlarmInstance Pointer to the timer instance to stop.
Marks the timer as inactive and resets its end time to the current wall time.
Definition at line 28 of file timer.c.
References timer_getWallTime(), timerAlarm::timerActive, and timerAlarm::timerEndTime.
Referenced by fsm_onDoorOpen(), fsm_spin(), and hmi_stopBtnHandler().